version: '3.8'

services:
  db:
    image: postgres:16-alpine
    container_name: sd-db
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: service_desk_db
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5

  api:
    build: ./backend-app
    container_name: sd-api
    restart: always
    environment:
      # Важно: здесь хост 'db' (имя сервиса), а не 'sd-db'
      DATABASE_URL: postgresql://postgres:postgres@db:5432/service_desk_db
    volumes:
      - media_data:/app/media
    depends_on:
      db:
        condition: service_healthy

  frontend:
    build: ./frontend-app
    container_name: sd-frontend
    restart: always
    environment:
      # Важно: используем имя сервиса 'api'
      - BACKEND_URL=http://api:8000
      - SECRET_KEY=super-secret-key-change-me
    ports:
      - "8001:5000"
    volumes:
      - media_data:/app/media
    depends_on:
      - api

volumes:
  postgres_data:
  media_data:
